---
title: "Explore treatment data in lung patients data"
author: "Christelle Colin-Leitzinger"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: true
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: kable
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
```

```{r library, echo = FALSE}
library(tidyverse)
library(labelled)
library(gtsummary)
theme_gtsummary_compact()
theme_set(theme_classic())
```

```{r load}
lung_data <- read_rds(paste0(here::here(), 
                            "/data/processed_data",
                 "/Lung_data_2026-05-27.rds"))
```

# Blood and treatment
```{r}
lung_data %>%
  select(treatment_sequence,
         drug_ever, radiation_ever,
         drug_radiation_ever,
         blood_before_drug,
         years_blood_before_drug,
         years_blood_after_drug,
         blood_before_rad,
         years_blood_before_rad,
         years_blood_after_rad,
         blood_before_drugorrad,
         years_blood_before_drugrad,
         years_blood_after_drugrad
         ) %>%
  tbl_summary(statistic = list(all_continuous() ~ "{median} ({p25}, {p75})", 
                               all_categorical() ~"{n} ({p}%)"),
              type = all_dichotomous() ~ "categorical",
              digits = list(all_continuous() ~ 1)) %>%
  bold_labels()
```

# Drugs
```{r}
lung_data %>%
  filter(drug_ever == "Yes") %>% 
  select(year_first_medication,
         treatment_sequence,
         drug_radiation_ever,
         blood_before_drug,
         years_blood_before_drug,
         years_blood_after_drug,
         
         blood_before_drugorrad,
         years_blood_before_drugrad,
         years_blood_after_drugrad,
         regimen_drugs_1
         ) %>%
  tbl_summary(statistic = list(all_continuous() ~ "{median} ({p25}, {p75})", 
                               all_categorical() ~"{n} ({p}%)"),
              digits = list(all_continuous() ~ 1)) %>%
  bold_labels()
```

```{r}
lung_data %>%
  filter(drug_ever == "Yes") %>% 
  filter(year_first_medication == 1900) %>% 
  select(ORIENAvatarKey, age_at_germline_collection, year_first_medication,
         AgeAtMedStart_1, AgeAtMedStart_2, regimen_drugs_1, AgeAtMedStop_1,
         year_first_radiation, AgeAtRadiationStart_1, AgeAtRadiationStart_2)
```



# Rad
```{r}
lung_data %>%
  filter(radiation_ever == "Yes") %>% 
  select(year_first_radiation,
         treatment_sequence,
         drug_radiation_ever,
         
         blood_before_rad,
         years_blood_before_rad,
         years_blood_after_rad,
         blood_before_drugorrad,
         years_blood_before_drugrad,
         years_blood_after_drugrad
         ) %>%
  tbl_summary(statistic = list(all_continuous() ~ "{median} ({p25}, {p75})", 
                               all_categorical() ~"{n} ({p}%)"),
              digits = list(all_continuous() ~ 1)) %>%
  bold_labels()
```












