---
title: "Untitled"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
```

```{r library}
library(tidyverse)
library(data.table)
library(labelled)
library(gtsummary)
library(survival)
library(survminer)
theme_set(theme_classic())
theme_gtsummary_compact()
```

```{r path}
path <- fs::path("", "Volumes", "Lab_Gillis","ORIEN_Avatar", "resources")
```


```{r load}
load("~/Documents/GitHub/Gillis/ch_orien/Rmd/R01 Gillis-Teng 2023-2024/initial_files.RData")

all_tumor_data <- read_rds(paste0(here::here(), "/Rmd/R01 Gillis-Teng 2023-2024/cleaned_all_tumor_type_data_06242024.rds"))
```

```{r Create new variables}
data <- all_tumor_data %>% 
  # Age at last contact
  mutate(is_agelastcontact_last_date = case_when(
    AgeAtLastContact >= age_at_lab                  ~ "Yes",
    AgeAtLastContact < age_at_lab                   ~ "No"
  )) %>% 
  mutate(AgeAtLastContact = case_when(
    is_agelastcontact_last_date == "Yes"            ~ AgeAtLastContact,
    is_agelastcontact_last_date == "No"             ~ age_at_lab
  )) %>% 
  # Age at first treatment
  mutate(first_treatment = case_when(
    (AgeAtRadiationStart < AgeAtSurgeryBiopsy |
      (is.na(AgeAtSurgeryBiopsy) &
         !is.na(AgeAtRadiationStart))) &
      
      (AgeAtRadiationStart < AgeAtMedStart_1 |
    (is.na(AgeAtMedStart_1) &
         !is.na(AgeAtRadiationStart))) &
      
      (AgeAtRadiationStart < AgeAtTransplant | 
         (is.na(AgeAtTransplant) &
         !is.na(AgeAtRadiationStart)))              ~ "Radiation",
    
    (AgeAtSurgeryBiopsy < AgeAtRadiationStart | 
         (is.na(AgeAtRadiationStart) &
         !is.na(AgeAtSurgeryBiopsy))) &
      
      (AgeAtSurgeryBiopsy < AgeAtMedStart_1 |
    (is.na(AgeAtMedStart_1) &
         !is.na(AgeAtSurgeryBiopsy))) &
      
      (AgeAtSurgeryBiopsy < AgeAtTransplant | 
         (is.na(AgeAtTransplant) &
         !is.na(AgeAtSurgeryBiopsy)))          ~ "Surgery",
    
    (AgeAtMedStart_1 < AgeAtRadiationStart | 
         (is.na(AgeAtRadiationStart) &
         !is.na(AgeAtMedStart_1))) &
      
      (AgeAtMedStart_1 < AgeAtSurgeryBiopsy |
      (is.na(AgeAtSurgeryBiopsy) &
         !is.na(AgeAtMedStart_1))) &
      
      (AgeAtMedStart_1 < AgeAtTransplant | 
         (is.na(AgeAtTransplant) &
         !is.na(AgeAtMedStart_1)))             ~ "Drugs",
    
    (AgeAtTransplant < AgeAtRadiationStart | 
         (is.na(AgeAtRadiationStart) &
         !is.na(AgeAtTransplant))) &
      
      (AgeAtTransplant < AgeAtSurgeryBiopsy |
      (is.na(AgeAtSurgeryBiopsy) &
         !is.na(AgeAtTransplant))) &
      
      (AgeAtTransplant < AgeAtMedStart_1 |
    (is.na(AgeAtMedStart_1) &
         !is.na(AgeAtTransplant)))             ~ "SCT"
    
  )) %>% 
  mutate(age_at_first_treatment = case_when(
    first_treatment == "Radiation"                  ~ AgeAtRadiationStart,
    first_treatment == "Surgery"                    ~ AgeAtSurgeryBiopsy,
    first_treatment == "Drugs"                      ~ AgeAtMedStart_1,
    first_treatment == "SCT"                        ~ AgeAtTransplant,
  )) %>% 
  # OS
  mutate(os_event = case_when(
    VitalStatus == "Alive"                          ~ 0,
    TRUE                                            ~ 1
  )) %>% 
  mutate(os_age = coalesce(AgeAtDeath, AgeAtLastContact)) %>% 
  mutate(os_time_from_dx_years = os_age - AgeAtDiagnosis) %>% 
  mutate(os_time_from_treatment_years = os_age - age_at_first_treatment) %>% 
  # PFS
  mutate(pfs_event = case_when(
    ProgRecurInd == "No"                            ~ 0,
    ProgRecurInd == "Progression"                   ~ 1,
    ProgRecurInd == "Recurrence"                    ~ 1
  )) %>% 
  mutate(pfs_age = coalesce(AgeAtProgRecur, AgeAtLastContact)) %>% 
  mutate(pfs_time_from_dx_years = pfs_age - AgeAtDiagnosis) %>% 
  mutate(pfs_time_from_treatment_years = pfs_age - age_at_first_treatment) %>% 
  # Metastasis
  mutate(pfs_event = case_when(
    had_metastasis == "Yes"                         ~ 1,
    is.na(had_metastasis)                           ~ 0
  )) %>% 
  mutate(met_age = coalesce(AgeAtMetastaticSite, AgeAtLastContact)) %>% 
  mutate(met_time_from_dx_years = met_age - AgeAtDiagnosis) %>% 
  mutate(met_time_from_treatment_years = met_age - age_at_first_treatment)
```


```{r labeling}
var_label(data) <- list(AgeAtDiagnosis = "Patient age at diagnosis?", germline_collection_age = "Age at blood collection",
                        race_eth = "Race/Ethnicity", PrimaryDiagnosisSite = "Primary Site",
                        ClinGroupStage = "Clinical Stage?", BodyWeight = "Body Weight",
                        BodyHeight = "Body Height", bmi_cat = "BMI categories",
                        SmokingStatus = "Smoking Status",
                        first_treatment = "First Treatment Type",
                        drugs_ever = "Drugs Ever", AgeAtMedStart_1 = "Age at First Drug",
                        Medication_1 = "First Regimen",
                        sct_ever = "Transplant Ever", AgeAtTransplant = "Age at Transplant",
                        radiation_ever = "Radiation Ever", AgeAtRadiationStart = "Age at Radiation",
                        surgery_ever = "Surgery Ever", AgeAtSurgeryBiopsy = "Age at Surgery",
                        had_metastasis = "Metastasis?", AgeAtMetastaticSite = "Age at Metastasis"
)
```

```{r}
data <- data %>% 
  filter(!is.na(CH_status_using_BickWHO)) %>% 
  mutate(CH_status_using_BickWHO = factor(CH_status_using_BickWHO, levels = c("No CH", "CH")))
```

## IV. Multiple Myeloma
```{r}
mm_data <- data %>% 
  filter(Disease.Type == "HEM - Myeloma Spectrum") %>% 
  mutate(iss_stage = case_when(
    str_detect(iss_stage, "III")      ~ "III",
    str_detect(iss_stage, "II")       ~ "II",
    str_detect(iss_stage, "I")        ~ "I"
  ), iss_stage = factor(iss_stage, 
                             levels = c("I", "II", 
                                        "III")))
```

Clean diagnosis
```{r}
mm_data %>% 
  select(AvatarKey, primar, Histology, subse)
  
  
  
  
  
  
```




















